### ISSUE TITLE
PocketMine-MP 1.4 에서는 어떻하실거예요?

### ISSUE THREAD

**Issue by cloud9350** [KOMC/EntityMove#20]
5달째 업데이트를 안하고 있는데, 이번 PocketMine-MP 업데이트는 어떻게 하실지 궁금하네요.

**Comment by cloud9350** [comment]
@ns827 음 언제 이 프로젝트가 다시 살아날지 궁금합니다..

**Comment by yale2a1** [comment]
이야 오랜만이네요

**Comment by ns827** [comment]
다 생존해계시네...!

**Comment by yale2a1** [comment]
@ns827 당연히 생존해 있습니다 ㅋ :D
이제 깃허브 다시 시작할렵니다.

**Comment by ns827** [comment]
:D
저는 그냥 웹개발 자체를 보고있는데 CSS가 암이네요 :P

**Comment by cloud9350** [comment]
@ns827 아 CSS는 그냥 정의하는것이 다죠 ㅎㅎ <웹전문
그자서나 기다리는 사람이 많습니다(!)

**Comment by yale2a1** [comment]
@cloud9350 기다리는 사람??

뭔 뜻인가요?

**Comment by yale2a1** [comment]
@cloud9350 그리고 깃허브 학생등록 하는법좀....

**Comment by cloud9350** [comment]
@yale2a1 엠코에 1.4로 Rewrite 한다면서 아직도 안되고있다는 함정때문에(!)
학생등록은 뭐예요 ㅋㅋ

**Comment by yale2a1** [comment]
@cloud9350 프로필에 학생표시가 있는데요?
근데 저하고 초면인가요?

**Comment by cloud9350** [comment]
@yale2a1 음..? 처음보는..
